#设置端口
server:
  port: 80
#数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource

